package com.ichaoj.ycl.client.beans;

import com.ichaoj.ycl.client.enums.GroupsEnum;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class YclSignatory implements Serializable {

	/**
	 * @mbggenerated
	 */
	private Long signatoryId;
	/**
	 * 待签约文件存储ID
	 * @mbggenerated
	 */
	private Long storeId;
	/**
	 * 签约人ID
	 * @mbggenerated
	 */
	private Long signatoryUserId;
	/**
	 * 签约时间
	 * @mbggenerated
	 */
	private String signatoryTime;
	/**
	 * 签约人类型(personal enterprise)
	 * @mbggenerated
	 */
	private String signatoryUserType;
	/**
	 * 是否自动签章
	 * @mbggenerated
	 */
	private String signatoryAuto;
	/**
	 * 签约人真实姓名
	 * @mbggenerated
	 */
	private String realName;
	/**
	 * 签约人电话
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * 签约人邮箱
	 * @mbggenerated
	 */
	private String email;
	/**
	 * 未签，已签
	 * @mbggenerated
	 */
	private String status;
	/**
	 * 是否系统用户
	 * @mbggenerated
	 */
	private String sysUser;
	/**
	 * 签约分组
	 * @mbggenerated
	 */
	private String groupChar;
	/**
	 * 签约分组名
	 * @mbggenerated
	 */
	private String groupName;
	/**
	 * 分组顺序
	 * @mbggenerated
	 */
	private Integer groupOrder;
	/**
	 * 签章页
	 * @mbggenerated
	 */
	private Integer signaturePage;
	/**
	 * 签章x坐标
	 * @mbggenerated
	 */
	private Double signatureX;
	/**
	 * 签章y坐标
	 * @mbggenerated
	 */
	private Double signatureY;
	/**
	 * 签章顺序
	 * @mbggenerated
	 */
	private Integer signatoryOrder;
	/**
	 * 图章类型(公章official 私章personal)
	 * @mbggenerated
	 */
	private String sealType;
	/**
	 * 签约人备注
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * @mbggenerated
	 */
	private Date rowUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ycl_signatory
	 * @mbg.generated  Fri Jan 26 15:28:58 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 证件号码
	 */
	private String certNo;

	/**
	 * 证件类型
	 */
	private String certType;

	public String getCertNo() {
		return certNo;
	}

	public void setCertNo(String certNo) {
		this.certNo = certNo;
	}

	public String getCertType() {
		return certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	/**
	 * @mbggenerated
	 */
	public Long getSignatoryId() {
		return signatoryId;
	}

	/**
	 * @param signatoryId  
	 * @mbggenerated
	 */
	public void setSignatoryId(Long signatoryId) {
		this.signatoryId = signatoryId;
	}

	/**
	 * 待签约文件存储ID
	 * @mbggenerated
	 */
	public Long getStoreId() {
		return storeId;
	}

	/**
	 * 待签约文件存储ID
	 * @param storeId  待签约文件存储ID
	 * @mbggenerated
	 */
	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	/**
	 * 签约人ID
	 * @mbggenerated
	 */
	public Long getSignatoryUserId() {
		return signatoryUserId;
	}

	/**
	 * 签约人ID
	 * @param signatoryUserId  签约人ID
	 * @mbggenerated
	 */
	public void setSignatoryUserId(Long signatoryUserId) {
		this.signatoryUserId = signatoryUserId;
	}

	/**
	 * 签约时间
	 * @mbggenerated
	 */
	public String getSignatoryTime() {
		return signatoryTime;
	}

	/**
	 * 签约时间
	 * @param signatoryTime  签约时间
	 * @mbggenerated
	 */
	public void setSignatoryTime(String signatoryTime) {
		this.signatoryTime = signatoryTime;
	}

	/**
	 * 签约人类型(personal enterprise)
	 * @mbggenerated
	 */
	public String getSignatoryUserType() {
		return signatoryUserType;
	}

	/**
	 * 签约人类型(personal enterprise)
	 * @param signatoryUserType  签约人类型(personal enterprise)
	 * @mbggenerated
	 */
	public void setSignatoryUserType(String signatoryUserType) {
		this.signatoryUserType = signatoryUserType == null ? null : signatoryUserType.trim();
	}

	/**
	 * 是否自动签章
	 * @mbggenerated
	 */
	public String getSignatoryAuto() {
		return signatoryAuto;
	}

	/**
	 * 是否自动签章
	 * @param signatoryAuto  是否自动签章
	 * @mbggenerated
	 */
	public void setSignatoryAuto(String signatoryAuto) {
		this.signatoryAuto = signatoryAuto == null ? null : signatoryAuto.trim();
	}

	/**
	 * 签约人真实姓名
	 * @mbggenerated
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * 签约人真实姓名
	 * @param realName  签约人真实姓名
	 * @mbggenerated
	 */
	public void setRealName(String realName) {
		this.realName = realName == null ? null : realName.trim();
	}

	/**
	 * 签约人电话
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * 签约人电话
	 * @param phone  签约人电话
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * 签约人邮箱
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * 签约人邮箱
	 * @param email  签约人邮箱
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * 未签，已签
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * 未签，已签
	 * @param status  未签，已签
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * 是否系统用户
	 * @mbggenerated
	 */
	public String getSysUser() {
		return sysUser;
	}

	/**
	 * 是否系统用户
	 * @param sysUser  是否系统用户
	 * @mbggenerated
	 */
	public void setSysUser(String sysUser) {
		this.sysUser = sysUser == null ? null : sysUser.trim();
	}

	/**
	 * 签约分组
	 * @mbggenerated
	 */
	public String getGroupChar() {
		return groupChar;
	}

	/**
	 * 签约分组
	 * @param groupChar  签约分组
	 * @mbggenerated
	 */
	public void setGroupChar(String groupChar) {
		this.groupChar = groupChar == null ? null : groupChar.trim();
	}

	/**
	 * 签约分组名
	 * @mbggenerated
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * 签约分组名
	 * @param groupName  签约分组名
	 * @mbggenerated
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName == null ? null : groupName.trim();
	}

	/**
	 * 设置签约方
	 * @param group
	 */
	public void setGroup(GroupsEnum group){
		Objects.requireNonNull(group);
		setGroupChar(group.getGroupChar());
		setGroupName(group.getGroupName());
	}
	/**
	 * 分组顺序
	 * @mbggenerated
	 */
	public Integer getGroupOrder() {
		return groupOrder;
	}

	/**
	 * 分组顺序
	 * @param groupOrder  分组顺序
	 * @mbggenerated
	 */
	public void setGroupOrder(Integer groupOrder) {
		this.groupOrder = groupOrder;
	}

	/**
	 * 签章页
	 * @mbggenerated
	 */
	public Integer getSignaturePage() {
		return signaturePage;
	}

	/**
	 * 签章页
	 * @param signaturePage  签章页
	 * @mbggenerated
	 */
	public void setSignaturePage(Integer signaturePage) {
		this.signaturePage = signaturePage;
	}

	/**
	 * 签章x坐标
	 * @mbggenerated
	 */
	public Double getSignatureX() {
		return signatureX;
	}

	/**
	 * 签章x坐标
	 * @param signatureX  签章x坐标
	 * @mbggenerated
	 */
	public void setSignatureX(Double signatureX) {
		this.signatureX = signatureX;
	}

	/**
	 * 签章y坐标
	 * @mbggenerated
	 */
	public Double getSignatureY() {
		return signatureY;
	}

	/**
	 * 签章y坐标
	 * @param signatureY  签章y坐标
	 * @mbggenerated
	 */
	public void setSignatureY(Double signatureY) {
		this.signatureY = signatureY;
	}

	/**
	 * 签章顺序
	 * @mbggenerated
	 */
	public Integer getSignatoryOrder() {
		return signatoryOrder;
	}

	/**
	 * 签章顺序
	 * @param signatoryOrder  签章顺序
	 * @mbggenerated
	 */
	public void setSignatoryOrder(Integer signatoryOrder) {
		this.signatoryOrder = signatoryOrder;
	}

	/**
	 * 图章类型(公章official 私章personal)
	 * @mbggenerated
	 */
	public String getSealType() {
		return sealType;
	}

	/**
	 * 图章类型(公章official 私章personal)
	 * @param sealType  图章类型(公章official 私章personal)
	 * @mbggenerated
	 */
	public void setSealType(String sealType) {
		this.sealType = sealType == null ? null : sealType.trim();
	}

	/**
	 * 签约人备注
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * 签约人备注
	 * @param remark  签约人备注
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * @mbggenerated
	 */
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * @param rowAddTime  
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * @mbggenerated
	 */
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * @param rowUpdateTime  
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ycl_signatory
	 * @mbg.generated  Fri Jan 26 15:28:58 CST 2018
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", signatoryId=").append(signatoryId);
		sb.append(", storeId=").append(storeId);
		sb.append(", signatoryUserId=").append(signatoryUserId);
		sb.append(", signatoryTime=").append(signatoryTime);
		sb.append(", signatoryUserType=").append(signatoryUserType);
		sb.append(", signatoryAuto=").append(signatoryAuto);
		sb.append(", realName=").append(realName);
		sb.append(", phone=").append(phone);
		sb.append(", email=").append(email);
		sb.append(", status=").append(status);
		sb.append(", sysUser=").append(sysUser);
		sb.append(", groupChar=").append(groupChar);
		sb.append(", groupName=").append(groupName);
		sb.append(", groupOrder=").append(groupOrder);
		sb.append(", signaturePage=").append(signaturePage);
		sb.append(", signatureX=").append(signatureX);
		sb.append(", signatureY=").append(signatureY);
		sb.append(", signatoryOrder=").append(signatoryOrder);
		sb.append(", sealType=").append(sealType);
		sb.append(", remark=").append(remark);
		sb.append(", rowAddTime=").append(rowAddTime);
		sb.append(", rowUpdateTime=").append(rowUpdateTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}