package com.bornsoft.ycl.client.beans;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;


public class YclDataStore implements Serializable {
	
	/**
	 * @mbggenerated
	 */
	private Long storeId;

	/**
	 * 数据拥有者ID
	 * @mbggenerated
	 */
	private Long ownerId;

	/**
	 * 用户业务ID
	 * @mbggenerated
	 */
	private String userBizNumber;

	/**
	 * 签约人列表，逗号分隔
	 * @mbggenerated
	 */
	private String signatoryNames;

	/**
	 * 存储来源，本地上传，API，合同
	 * @mbggenerated
	 */
	private String source;

	/**
	 * 合同名称
	 * @mbggenerated
	 */
	private String storeName;

	/**
	 * 文件类型
	 * @mbggenerated
	 */
	private String fileType;

	/**
	 * 合同类型
	 * @mbggenerated
	 */
	private String contractStatus;

	/**
	 * 数据隶属通道
	 * @mbggenerated
	 */
	private String channel;

	/**
	 * 合同金额
	 * @mbggenerated
	 */
	private Money contractAmount;

	/**
	 * 安全存储数据
	 * @mbggenerated
	 */
	private String storeData;

	/**
	 * 标签
	 * @mbggenerated
	 */
	private String tags;

	/**
	 * 商户名称
	 * @mbggenerated
	 */
	private String merchantName;

	/**
	 * 数据拥有者名字
	 * @mbggenerated
	 */
	private String ownerName;

	/**
	 * 交易摘要
	 * @mbggenerated
	 */
	private String transAbs;

	/**
	 * @mbggenerated
	 */
	private String appKey;

	/**
	 * @mbggenerated
	 */
	private String appSecret;

	/**
	 * 原始文件名
	 * @mbggenerated
	 */
	private String fileName;

	/**
	 * 存储文件路径
	 * @mbggenerated
	 */
	private String filePath;

	/**
	 * 文件url地址
	 * @mbggenerated
	 */
	private String fileUrl;

	/**
	 * pdf快照图片路径
	 * @mbggenerated
	 */
	private String snapshotPath;

	/**
	 * @mbggenerated
	 */
	private String snapshotUrl;

	/**
	 * hash值（区块链返回）
	 * @mbggenerated
	 */
	private String hashCode;

	/**
	 * 保存全时间
	 * @mbggenerated
	 */
	private Date saveTime;

	/**
	 * 是否公开
	 * @mbggenerated
	 */
	private String isPublic;

	/**
	 * @mbggenerated
	 */
	private String isBlocked;

	/**
	 * 数据签名
	 * @mbggenerated
	 */
	private String sign;

	/**
	 * @mbggenerated
	 */
	private Date rowUpdateTime;

	/**
	 * @mbggenerated
	 */
	private Date rowAddTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ycl_data_store
	 * @mbg.generated  Fri Jan 26 15:28:58 CST 2018
	 */
	private static final long serialVersionUID = 1L;


	/**
	 * @mbggenerated
	 */
	public Long getStoreId() {
		return storeId;
	}

	/**
	 * @param storeId  
	 * @mbggenerated
	 */
	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	/**
	 * 数据拥有者ID
	 * @mbggenerated
	 */
	public Long getOwnerId() {
		return ownerId;
	}

	/**
	 * 数据拥有者ID
	 * @param ownerId  数据拥有者ID
	 * @mbggenerated
	 */
	public void setOwnerId(Long ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * 用户业务ID
	 * @mbggenerated
	 */
	public String getUserBizNumber() {
		return userBizNumber;
	}

	/**
	 * 用户业务ID
	 * @param userBizNumber  用户业务ID
	 * @mbggenerated
	 */
	public void setUserBizNumber(String userBizNumber) {
		this.userBizNumber = userBizNumber == null ? null : userBizNumber.trim();
	}

	/**
	 * 签约人列表，逗号分隔
	 * @mbggenerated
	 */
	public String getSignatoryNames() {
		return signatoryNames;
	}

	/**
	 * 签约人列表，逗号分隔
	 * @param signatoryNames  签约人列表，逗号分隔
	 * @mbggenerated
	 */
	public void setSignatoryNames(String signatoryNames) {
		this.signatoryNames = signatoryNames == null ? null : signatoryNames.trim();
	}

	/**
	 * 存储来源，本地上传，API，合同
	 * @mbggenerated
	 */
	public String getSource() {
		return source;
	}

	/**
	 * 存储来源，本地上传，API，合同
	 * @param source  存储来源，本地上传，API，合同
	 * @mbggenerated
	 */
	public void setSource(String source) {
		this.source = source == null ? null : source.trim();
	}

	/**
	 * 合同名称
	 * @mbggenerated
	 */
	public String getStoreName() {
		return storeName;
	}

	/**
	 * 合同名称
	 * @param storeName  合同名称
	 * @mbggenerated
	 */
	public void setStoreName(String storeName) {
		this.storeName = storeName == null ? null : storeName.trim();
	}

	/**
	 * 文件类型
	 * @mbggenerated
	 */
	public String getFileType() {
		return fileType;
	}

	/**
	 * 文件类型
	 * @param fileType  文件类型
	 * @mbggenerated
	 */
	public void setFileType(String fileType) {
		this.fileType = fileType == null ? null : fileType.trim();
	}

	/**
	 * 合同类型
	 * @mbggenerated
	 */
	public String getContractStatus() {
		return contractStatus;
	}

	/**
	 * 合同类型
	 * @param contractStatus  合同类型
	 * @mbggenerated
	 */
	public void setContractStatus(String contractStatus) {
		this.contractStatus = contractStatus == null ? null : contractStatus.trim();
	}

	/**
	 * 数据隶属通道
	 * @mbggenerated
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * 数据隶属通道
	 * @param channel  数据隶属通道
	 * @mbggenerated
	 */
	public void setChannel(String channel) {
		this.channel = channel == null ? null : channel.trim();
	}

	/**
	 * 合同金额
	 * @mbggenerated
	 */
	public Money getContractAmount() {
		return contractAmount;
	}

	/**
	 * 合同金额
	 * @param contractAmount  合同金额
	 * @mbggenerated
	 */
	public void setContractAmount(Money contractAmount) {
		this.contractAmount = contractAmount;
	}

	/**
	 * 安全存储数据
	 * @mbggenerated
	 */
	public String getStoreData() {
		return storeData;
	}

	/**
	 * 安全存储数据
	 * @param storeData  安全存储数据
	 * @mbggenerated
	 */
	public void setStoreData(String storeData) {
		this.storeData = storeData == null ? null : storeData.trim();
	}

	/**
	 * 标签
	 * @mbggenerated
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * 标签
	 * @param tags  标签
	 * @mbggenerated
	 */
	public void setTags(String tags) {
		this.tags = tags == null ? null : tags.trim();
	}

	/**
	 * 商户名称
	 * @mbggenerated
	 */
	public String getMerchantName() {
		return merchantName;
	}

	/**
	 * 商户名称
	 * @param merchantName  商户名称
	 * @mbggenerated
	 */
	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName == null ? null : merchantName.trim();
	}

	/**
	 * 数据拥有者名字
	 * @mbggenerated
	 */
	public String getOwnerName() {
		return ownerName;
	}

	/**
	 * 数据拥有者名字
	 * @param ownerName  数据拥有者名字
	 * @mbggenerated
	 */
	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName == null ? null : ownerName.trim();
	}

	/**
	 * 交易摘要
	 * @mbggenerated
	 */
	public String getTransAbs() {
		return transAbs;
	}

	/**
	 * 交易摘要
	 * @param transAbs  交易摘要
	 * @mbggenerated
	 */
	public void setTransAbs(String transAbs) {
		this.transAbs = transAbs == null ? null : transAbs.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getAppKey() {
		return appKey;
	}

	/**
	 * @param appKey  
	 * @mbggenerated
	 */
	public void setAppKey(String appKey) {
		this.appKey = appKey == null ? null : appKey.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getAppSecret() {
		return appSecret;
	}

	/**
	 * @param appSecret  
	 * @mbggenerated
	 */
	public void setAppSecret(String appSecret) {
		this.appSecret = appSecret == null ? null : appSecret.trim();
	}

	/**
	 * 原始文件名
	 * @mbggenerated
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * 原始文件名
	 * @param fileName  原始文件名
	 * @mbggenerated
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}

	/**
	 * 存储文件路径
	 * @mbggenerated
	 */
	public String getFilePath() {
		return filePath;
	}

	/**
	 * 存储文件路径
	 * @param filePath  存储文件路径
	 * @mbggenerated
	 */
	public void setFilePath(String filePath) {
		this.filePath = filePath == null ? null : filePath.trim();
	}

	/**
	 * 文件url地址
	 * @mbggenerated
	 */
	public String getFileUrl() {
		return fileUrl;
	}

	/**
	 * 文件url地址
	 * @param fileUrl  文件url地址
	 * @mbggenerated
	 */
	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl == null ? null : fileUrl.trim();
	}

	/**
	 * pdf快照图片路径
	 * @mbggenerated
	 */
	public String getSnapshotPath() {
		return snapshotPath;
	}

	/**
	 * pdf快照图片路径
	 * @param snapshotPath  pdf快照图片路径
	 * @mbggenerated
	 */
	public void setSnapshotPath(String snapshotPath) {
		this.snapshotPath = snapshotPath == null ? null : snapshotPath.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getSnapshotUrl() {
		return snapshotUrl;
	}

	/**
	 * @param snapshotUrl  
	 * @mbggenerated
	 */
	public void setSnapshotUrl(String snapshotUrl) {
		this.snapshotUrl = snapshotUrl == null ? null : snapshotUrl.trim();
	}

	/**
	 * hash值（区块链返回）
	 * @mbggenerated
	 */
	public String getHashCode() {
		return hashCode;
	}

	/**
	 * hash值（区块链返回）
	 * @param hashCode  hash值（区块链返回）
	 * @mbggenerated
	 */
	public void setHashCode(String hashCode) {
		this.hashCode = hashCode == null ? null : hashCode.trim();
	}

	/**
	 * 保存全时间
	 * @mbggenerated
	 */
	public Date getSaveTime() {
		return saveTime;
	}

	/**
	 * 保存全时间
	 * @param saveTime  保存全时间
	 * @mbggenerated
	 */
	public void setSaveTime(Date saveTime) {
		this.saveTime = saveTime;
	}

	/**
	 * 是否公开
	 * @mbggenerated
	 */
	public String getIsPublic() {
		return isPublic;
	}

	/**
	 * 是否公开
	 * @param isPublic  是否公开
	 * @mbggenerated
	 */
	public void setIsPublic(String isPublic) {
		this.isPublic = isPublic == null ? null : isPublic.trim();
	}

	/**
	 * @mbggenerated
	 */
	public String getIsBlocked() {
		return isBlocked;
	}

	/**
	 * @param isBlocked  
	 * @mbggenerated
	 */
	public void setIsBlocked(String isBlocked) {
		this.isBlocked = isBlocked == null ? null : isBlocked.trim();
	}

	/**
	 * 数据签名
	 * @mbggenerated
	 */
	public String getSign() {
		return sign;
	}

	/**
	 * 数据签名
	 * @param sign  数据签名
	 * @mbggenerated
	 */
	public void setSign(String sign) {
		this.sign = sign == null ? null : sign.trim();
	}

	/**
	 * @mbggenerated
	 */
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * @param rowUpdateTime  
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}

	/**
	 * @mbggenerated
	 */
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * @param rowAddTime  
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ycl_data_store
	 * @mbg.generated  Fri Jan 26 15:28:58 CST 2018
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", storeId=").append(storeId);
		sb.append(", ownerId=").append(ownerId);
		sb.append(", userBizNumber=").append(userBizNumber);
		sb.append(", signatoryNames=").append(signatoryNames);
		sb.append(", source=").append(source);
		sb.append(", storeName=").append(storeName);
		sb.append(", fileType=").append(fileType);
		sb.append(", contractStatus=").append(contractStatus);
		sb.append(", channel=").append(channel);
		sb.append(", contractAmount=").append(contractAmount);
		sb.append(", storeData=").append(storeData);
		sb.append(", tags=").append(tags);
		sb.append(", merchantName=").append(merchantName);
		sb.append(", ownerName=").append(ownerName);
		sb.append(", transAbs=").append(transAbs);
		sb.append(", appKey=").append(appKey);
		sb.append(", appSecret=").append(appSecret);
		sb.append(", fileName=").append(fileName);
		sb.append(", filePath=").append(filePath);
		sb.append(", fileUrl=").append(fileUrl);
		sb.append(", snapshotPath=").append(snapshotPath);
		sb.append(", snapshotUrl=").append(snapshotUrl);
		sb.append(", hashCode=").append(hashCode);
		sb.append(", saveTime=").append(saveTime);
		sb.append(", isPublic=").append(isPublic);
		sb.append(", isBlocked=").append(isBlocked);
		sb.append(", sign=").append(sign);
		sb.append(", rowUpdateTime=").append(rowUpdateTime);
		sb.append(", rowAddTime=").append(rowAddTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	private DecimalFormat format = new DecimalFormat("YC0000000000");

	private List<YclSignatory> yclSignatorys;
	

	public List<YclSignatory> getYclSignatorys() {
		return yclSignatorys;
	}

	public void setYclSignatorys(List<YclSignatory> yclSignatorys) {
		this.yclSignatorys = yclSignatorys;
	}
	
	public String getStoreNo(){
		if(getStoreId() == null)
			return null;
		else
			return format.format(this.getStoreId());
	}
}